server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Dashboard
    location = / {
        try_files /index.html =404;
    }

    # API & Health Checks
    location /api/ {
        resolver 8.8.8.8;
        proxy_pass https://sipy-url-shortner-1.onrender.com;
        proxy_set_header Host $host;
    }

    location /health {
        resolver 8.8.8.8;
        proxy_pass https://sipy-url-shortner-1.onrender.com;
        proxy_set_header Host $host;
    }

    # Static Assets
    location /styles/ {
        try_files $uri =404;
    }
    
    location /scripts/ {
        try_files $uri =404;
    }
    
    location /favicon.ico {
        try_files $uri =404;
    }

    # Short Link Redirect
    location / {
        resolver 8.8.8.8;
        proxy_pass https://sipy-url-shortner-1.onrender.com;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_intercept_errors on;
        error_page 404 = /index.html;
    }
}